# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  schedule:
    - cron: '0 1 * * 1'
  push:
    branches: [main, master]
  pull_request:

name: R-CMD-check.yaml

permissions: read-all

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.runner }}

    name: ${{ matrix.config.os }} - ${{ matrix.config.platform }} (${{ matrix.config.r }})${{ matrix.config.torch && ' – with torch' || '' }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: "macos", r: "release", platform: "cpu" }
          - { os: "ubuntu", r: "release", platform: "cpu" }
          - { os: "ubuntu", r: "release", platform: "cpu", torch: true }
          - { os: "windows", r: "release", platform: "cpu"}

        include:
          - config: {os: "ubuntu", platform: "cpu"}
            runner: 'ubuntu-latest'
          - config: {os: "macos", platform: "cpu"}
            runner: 'macos-latest'
            setup: |
              brew install protobuf@21
              brew link protobuf@21 --force --overwrite
          - config: {os: "windows", platform: "cpu"}
            runner: 'windows-latest'

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      PJRT_PLATFORM: ${{ matrix.config.platform }}

    steps:
      - name: Setup
        if: ${{ matrix.setup }}
        run: ${{ matrix.setup }}

      - uses: actions/checkout@v5

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true
          extra-repositories: https://r-xla.r-universe.dev https://t-kalinowski.r-universe.dev

      - uses: ./.github/actions/r-check
        with:
          install-torch: ${{ matrix.config.torch == true }}

  R-CMD-check-cuda:
    needs: R-CMD-check
    runs-on: ['self-hosted', 'gpu']
    container:
      image: 'sebffischer/anvil-cuda-base:latest'
      options: '--gpus all --runtime=nvidia'

    name: ubuntu - cuda (release)

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      PJRT_PLATFORM: cuda

    steps:
      - uses: actions/checkout@v5

      - uses: ./.github/actions/r-check
